<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <BaseOutputPath Condition="Exists('/home/user/.cache')">/home/user/.cache/nativeload/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath Condition="Exists('/home/user/.cache')">/home/user/.cache/nativeload/obj/</BaseIntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../cs/SR2D.cs;Program.cs" />
  </ItemGroup>
  <Import Project="../../../cs/SR2D.Native.targets" />
</Project>
